"""2.3.3

Revision ID: 578c1c0553c3
Revises: 746caa1a290b
Create Date: 2023-10-19 15:39:31.493335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578c1c0553c3'
down_revision = '746caa1a290b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vadmin_redbook_images',
    sa.Column('noteurl', sa.String(length=255), nullable=False, comment='笔记url'),
    sa.Column('notetype', sa.String(length=8), nullable=True, comment='笔记类型'),
    sa.Column('notetitle', sa.String(length=50), nullable=False, comment='笔记标题'),
    sa.Column('notedescription', sa.String(length=500), nullable=False, comment='笔记描述'),
    sa.Column('notetags', sa.String(length=255), nullable=False, comment='笔记标签'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='原图片名称'),
    sa.Column('image_url', sa.String(length=500), nullable=False, comment='图片链接'),
    sa.Column('create_user_id', sa.Integer(), nullable=False, comment='创建人'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否软删除'),
    sa.ForeignKeyConstraint(['create_user_id'], ['vadmin_auth_user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='小红书素材表'
    )
    op.create_index(op.f('ix_vadmin_redbook_images_notetitle'), 'vadmin_redbook_images', ['notetitle'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vadmin_redbook_images_notetitle'), table_name='vadmin_redbook_images')
    op.drop_table('vadmin_redbook_images')
    # ### end Alembic commands ###
