"""3.6.4

Revision ID: b4dc6b7e0aef
Revises: dbf94b2ef7ca
Create Date: 2024-02-01 14:41:06.073700

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4dc6b7e0aef'
down_revision = 'dbf94b2ef7ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'red_book_urls',
        sa.Column('red_book_id', sa.Integer(), nullable=False),
        sa.Column('url', sa.String(length=255), nullable=False, comment='下载地址'),
        sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
        sa.Column(
            'create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'
        ),
        sa.Column(
            'update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'
        ),
        sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='删除时间'),
        sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否软删除 0 非删除 1 删除'),
        sa.ForeignKeyConstraint(['red_book_id'], ['red_book.id'], ),
        sa.PrimaryKeyConstraint('id'),
        comment='小红书下载链接'
    )
    op.alter_column(
        'api_info', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'api_info', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'api_report', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'api_report', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'api_test_report_detail', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'api_test_report_detail', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'data_source', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'data_source', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'env_management', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'env_management', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'functions', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'functions', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'module_info', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'module_info', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'project_info', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'project_info', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'red_book', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'red_book', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.drop_column('red_book', 'url')
    op.alter_column(
        'test_case', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'test_case', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_auth_dept', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_auth_dept', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_auth_menu', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_auth_menu', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_auth_role', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_auth_role', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_auth_user', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_auth_user', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_help_issue', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_help_issue', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_help_issue_category', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_help_issue_category', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_record_login', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_record_login', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_record_sms_send', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_record_sms_send', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_resource_images', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_resource_images', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_system_dict_details', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_system_dict_details', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_system_dict_type', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_system_dict_type', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_system_settings', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_system_settings', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_system_settings_tab', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_system_settings_tab', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'vadmin_system_settings_tab', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_system_settings_tab', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_system_settings', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_system_settings', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_system_dict_type', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_system_dict_type', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_system_dict_details', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_system_dict_details', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_resource_images', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_resource_images', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_record_sms_send', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_record_sms_send', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_record_login', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_record_login', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_help_issue_category', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_help_issue_category', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_help_issue', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_help_issue', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_auth_user', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_auth_user', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_auth_role', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_auth_role', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_auth_menu', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_auth_menu', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_auth_dept', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_auth_dept', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'test_case', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'test_case', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.add_column('red_book', sa.Column('url', mysql.VARCHAR(length=255), nullable=False, comment='下载地址'))
    op.alter_column(
        'red_book', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'red_book', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'project_info', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'project_info', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'module_info', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'module_info', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'functions', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'functions', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'env_management', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'env_management', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'data_source', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'data_source', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'api_test_report_detail', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'api_test_report_detail', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'api_report', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'api_report', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'api_info', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'api_info', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.drop_table('red_book_urls')
    # ### end Alembic commands ###
