"""3.6.4

Revision ID: dbf94b2ef7ca
Revises: 71521eeca6b2
Create Date: 2024-02-01 10:01:17.779237

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dbf94b2ef7ca'
down_revision = '71521eeca6b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'api_info', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'api_info', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'api_report', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'api_report', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'api_test_report_detail', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'api_test_report_detail', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'data_source', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'data_source', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'env_management', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'env_management', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'functions', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'functions', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'module_info', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'module_info', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'project_info', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'project_info', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.add_column('red_book', sa.Column('create_user_id', sa.Integer(), nullable=False, comment='创建人'))
    op.alter_column(
        'red_book', 'tags',
        existing_type=mysql.VARCHAR(length=512),
        type_=sa.String(length=50),
        existing_comment='标签',
        existing_nullable=False
    )
    op.alter_column(
        'red_book', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'red_book', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.create_foreign_key(None, 'red_book', 'vadmin_auth_user', ['create_user_id'], ['id'], ondelete='RESTRICT')
    op.create_table_comment(
        'red_book',
        '小红书素材表',
        existing_comment='小红书资源表',
        schema=None
    )
    op.alter_column(
        'test_case', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'test_case', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_auth_dept', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_auth_dept', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_auth_menu', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_auth_menu', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_auth_role', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_auth_role', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_auth_user', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_auth_user', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_help_issue', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_help_issue', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_help_issue_category', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_help_issue_category', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_record_login', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_record_login', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_record_sms_send', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_record_sms_send', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_resource_images', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_resource_images', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_system_dict_details', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_system_dict_details', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_system_dict_type', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_system_dict_type', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_system_settings', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_system_settings', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_system_settings_tab', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_system_settings_tab', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'vadmin_system_settings_tab', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_system_settings_tab', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_system_settings', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_system_settings', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_system_dict_type', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_system_dict_type', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_system_dict_details', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_system_dict_details', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_resource_images', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_resource_images', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_record_sms_send', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_record_sms_send', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_record_login', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_record_login', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_help_issue_category', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_help_issue_category', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_help_issue', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_help_issue', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_auth_user', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_auth_user', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_auth_role', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_auth_role', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_auth_menu', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_auth_menu', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_auth_dept', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'vadmin_auth_dept', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'test_case', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'test_case', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.create_table_comment(
        'red_book',
        '小红书资源表',
        existing_comment='小红书素材表',
        schema=None
    )
    op.drop_constraint(None, 'red_book', type_='foreignkey')
    op.alter_column(
        'red_book', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'red_book', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'red_book', 'tags',
        existing_type=sa.String(length=50),
        type_=mysql.VARCHAR(length=512),
        existing_comment='标签',
        existing_nullable=False
    )
    op.drop_column('red_book', 'create_user_id')
    op.alter_column(
        'project_info', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'project_info', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'module_info', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'module_info', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'functions', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'functions', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'env_management', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'env_management', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'data_source', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'data_source', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'api_test_report_detail', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'api_test_report_detail', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'api_report', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'api_report', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    op.alter_column(
        'api_info', 'update_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='更新时间',
        existing_nullable=False
    )
    op.alter_column(
        'api_info', 'create_datetime',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_comment='创建时间',
        existing_nullable=False
    )
    # ### end Alembic commands ###
