# Select the image to build based on SERVER_TYPE, defaulting to fastapi_server, or docker-compose build args
ARG SERVER_TYPE=fastapi_server

FROM tiangolo/uvicorn-gunicorn:python3.10-slim AS builder

LABEL maintainer="ranyong"

WORKDIR /Sakura_k

# 安装必要的构建工具
RUN apt-get update && apt-get install -y g++ && rm -rf /var/lib/apt/lists/*

# 复制依赖文件
COPY pyproject.toml ./

# 安装 uv 并使用它来安装依赖
RUN pip3 install --upgrade pip && \
    pip3 install uv && \
    # 使用 uv pip 直接从 pyproject.toml 安装依赖
    uv pip install --system -e .

# 复制剩余文件
COPY . .
COPY .env.docker ./.env

RUN if [ -f ".env.docker" ]; then mv .env.docker .env; fi

# 使用 python 直接运行应用
CMD ["python", "app.py"]