version: "3"
services:
  sakura_k:
    container_name: sakura_k
    restart: always
    ports:
      - "9099:9099"
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      TZ: "Asia/Shanghai"
      REDIS_HOST: redis
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: Ranyong_520
      MYSQL_DATABASE: ruoyi-fastapi
      MYSQL_PORT: 3306
    volumes:
      - ../sakura_k:/app
    depends_on:
      - redis
      - mysql

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6380:6379"

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD: Ranyong_520
      MYSQL_DATABASE: ruoyi-fastapi
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: