version: "3"
services:
  sakura_k:
    container_name: sakura_k
    restart: always
    ports:
      - "9099:9099"
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ../sakura_k:/app
    networks:
      sakura_network:
        ipv4_address: "192.168.0.2"

#  sakura-task:
#    container_name: sakura-task
#    restart: always
#    build:
#      context: ./
#      Dockerfile: ./docker_env/sakura_task/Dockerfile
#    environment:
#      TZ: "Asia/Shanghai"
#    volumes:
#      - .././sakura-task:/app
#    networks:
#      sakura_network:
#        ipv4_address: "177.8.0.4"


#  sakura-redis:
#    container_name: sakura-redis
#    restart: always
#    image: redis:latest
#    ports:
#      - "6379:6379"
#    expose:
#      - "6379"
#    volumes:
#      - ./docker_env/redis/conf/redis.conf:/etc/redis/redis.conf
#    environment:
#      TZ: "Asia/Shanghai"
#    networks:
#      sakura_network:
#        ipv4_address: "177.8.0.5"
#    command: redis-server /etc/redis/redis.conf
#
#
#  sakura-mysql:
#    container_name: sakura-mysql
#    restart: always
#    image: mysql:latest
#    ports:
#      - "3306:3306"
#    expose:
#      - "3306"
#    volumes:
#      - ./docker_env/mysql/conf:/etc/mysql/conf.d
#      - ./docker_env/mysql/data:/var/lib/mysql
#      - ./docker_env/mysql/logs:/logs
#    environment:
#      TZ: "Asia/Shanghai"
#      MYSQL_ROOT_USERNAME: "root"
#      MYSQL_ROOT_PASSWORD: "123456"
#      MYSQL_DATABASE: "sakura_k"
#    networks:
#      sakura_network:
#        ipv4_address: "177.8.0.7"

networks:
  sakura_network:
    ipam:
      config:
        - subnet: "192.168.0.0/16"
